---
- name: restart critical services
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
  loop:
    - sshd
    - auditd
    - fail2ban

- name: reboot required
  debug:
    msg: "Kernel updated - Reboot required for changes to take effect"
  changed_when: true
  notify: reboot system

- name: reboot system
  reboot:
    reboot_timeout: 600
    msg: "Reboot initiated by Ansible for kernel update"
  listen: "reboot system"

- name: start qualys agent
  systemd:
    name: qualys-cloud-agent
    state: started
    enabled: yes